version: '3.4'
# Usage for any service
#   - Run shell inside container: docker-compose run --rm --service-ports SERVICE_NAME bash
services:
  rust_templates:
    build: .
    volumes:
      - .:/rust_templates
      - cargo_registry:/usr/local/cargo/registry/
    working_dir: /rust_templates

volumes:
  cargo_registry:
