version: '3.4'
# Usage for any service
#   - Run shell inside container: docker-compose run --rm --service-ports SERVICE_NAME bash
services:
  app:
    build: .
    volumes:
      - .:/app
      - cargo_registry:/usr/local/cargo/registry/
    working_dir: /app

volumes:
  cargo_registry:
